# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/pam
  block:

    - name: Set OS variables
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_first_found:
        - "{{ ansible_os_family|lower }}.yml"
        - "default.yml"

    - name: CIS | Ensure PAM and cracklib are installed
      become: true
      ansible.builtin.package:
        name: "{{ pam_packages }}"
        state: present

    - name: CIS | Ensure password creation requirements are configured (pwquality)
      become: true
      ansible.builtin.template:
        src: 'etc/security/pwquality.conf.j2'
        dest: '/etc/security/pwquality.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: CIS | Ensure lockout for failed password attempts is configured
      become: true
      ansible.builtin.template:
        src: 'etc/security/faillock.conf.j2'
        dest: '/etc/security/faillock.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: CIS | Create su group
      become: true
      ansible.builtin.group:
        name: "{{ pam_su_group }}"
        system: true
        state: present

    - name: CIS | Ensure access to the su command is restricted
      become: true
      ansible.builtin.template:
        src: "etc/pam.d/su-{{ ansible_os_family|lower }}.j2"
        dest: '/etc/pam.d/su'
        owner: 'root'
        group: 'root'
        mode: '0644'

    # ----------------------------------------------------------------------
    # Import OS specific configurations
    # ----------------------------------------------------------------------

    - name: Configure PAM
      ansible.builtin.import_tasks:
        file: "redhat.yml"
      when:
        - ansible_os_family|lower == "redhat"

    - name: Configure PAM
      ansible.builtin.import_tasks:
        file: "debian.yml"
      when:
        - ansible_os_family|lower == "debian"

    # ----------------------------------------------------------------------

    # Flush any handlers that we might have called
    - name: Flush handlers
      ansible.builtin.meta:
        flush_handlers

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_pam'
